# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicroEks < Formula
  desc "A lightweight local Kubernetes environment using Multipass and MicroK8s"
  homepage "https://github.com/arunsanna/MicroEKS"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.2/micro-eks_Darwin_x86_64.tar.gz"
      sha256 "12239aae75f77dec776c0298619a099bd46979f530dbae908311babe463207c6"

      def install
        bin.install "micro-eks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.2/micro-eks_Darwin_arm64.tar.gz"
      sha256 "b6c1565ba35c165e1672b393cda39fca0cb4ead403b0f8432cccd01ce4d77852"

      def install
        bin.install "micro-eks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.2/micro-eks_Linux_x86_64.tar.gz"
      sha256 "4236c90dba2faa4b3de61f6cd0c006e0ffaf36816eedc3706d858ad7c64d57d5"
      def install
        bin.install "micro-eks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.2/micro-eks_Linux_arm64.tar.gz"
      sha256 "0fbf4690ea2640411b300c20ca759bdc55d3232c3ea57afe691f5300de4553ef"
      def install
        bin.install "micro-eks"
      end
    end
  end

  test do
    system "#{bin}/micro-eks --help"
  end
end
