# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MicroEks < Formula
  desc "A lightweight local Kubernetes environment using Multipass and MicroK8s"
  homepage "https://github.com/arunsanna/MicroEKS"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.3/micro-eks_Darwin_x86_64.tar.gz"
      sha256 "011dbea3625ba0a27f744501fe628da45d2c6d48b3381ef3cab1bdccab4c5078"

      def install
        bin.install "micro-eks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.3/micro-eks_Darwin_arm64.tar.gz"
      sha256 "c6c397ab45698668d7ff84e9eecaa084d240018a4409e7e665cc5dfd5e60d8d9"

      def install
        bin.install "micro-eks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.3/micro-eks_Linux_x86_64.tar.gz"
      sha256 "25baf420517361f88e342cd168422ba0752df3418075f3846914fd56d08036a7"
      def install
        bin.install "micro-eks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arunsanna/MicroEKS/releases/download/v0.2.3/micro-eks_Linux_arm64.tar.gz"
      sha256 "622094996545301688ff9e788f0bf7f9ae31cd1b00ad5fdd95b866fcb9aa5cf2"
      def install
        bin.install "micro-eks"
      end
    end
  end

  test do
    system "#{bin}/micro-eks --help"
  end
end
